package com.inocen.easylaundrycustomer.HomeActivity;

import android.os.Bundle;

public class Satuan {
    static Bundle bundle = new Bundle();

    public static void initBundle() {
        bundle.putInt("Baju gamis", 27000);
        bundle.putInt("Baju kaos", 12500);
        bundle.putInt("Baju kaos kerah", 17000);
        bundle.putInt("Baju pengantin", 60000);
        bundle.putInt("Baju wisuda", 25000);
        bundle.putInt("Baju dalam", 4000);
        bundle.putInt("Bantal besar", 20000);
        bundle.putInt("Bantal kecil", 15000);
        bundle.putInt("Bantal guling", 15000);
        bundle.putInt("Bantal selimut", 20000);
        bundle.putInt("Bed cover double", 30000);
        bundle.putInt("Bed cover single", 25000);
        bundle.putInt("Blazer", 15000);
        bundle.putInt("Boneka extra besar", 50000);
        bundle.putInt("Boneka besar", 25000);
        bundle.putInt("Boneka sedang", 15000);
        bundle.putInt("Boneka kecil", 10000);
        bundle.putInt("Boneka mini", 5000);
        bundle.putInt("Blouse", 15000);
        bundle.putInt("Box bayi besar", 100000);
        bundle.putInt("Box bayi sedang", 80000);
        bundle.putInt("Box bayi kecil", 60000);
        bundle.putInt("Celana panjang", 20000);
        bundle.putInt("Celana 3/4", 15000);
        bundle.putInt("Celana pendek", 10000);
        bundle.putInt("Celana dalam", 4000);
        bundle.putInt("Dress variasi", 30000);
        bundle.putInt("Dress panjang", 20000);
        bundle.putInt("Dress pendek", 15000);
        bundle.putInt("Dalaman kebaya variasi", 10000);
        bundle.putInt("Dalaman kebaya", 7500);
        bundle.putInt("Dasi", 4000);
        bundle.putInt("Handuk besar", 10000);
        bundle.putInt("Handuk sedang", 7500);
        bundle.putInt("Handuk kecil", 5000);
        bundle.putInt("Jas", 35000);
        bundle.putInt("Jaket", 15000);
        bundle.putInt("Jaket kulit", 30000);
        bundle.putInt("Koper besar", 50000);
        bundle.putInt("Koper sedang", 40000);
        bundle.putInt("Koper kecil", 30000);
        bundle.putInt("Kelambu (m2)", 4000);
        bundle.putInt("Kebaya", 15000);
        bundle.putInt("Kemeja", 15000);
        bundle.putInt("Kemeja batik", 20000);
        bundle.putInt("Matras besar", 60000);
        bundle.putInt("Matras sedang", 45000);
        bundle.putInt("Matras kecil", 30000);
        bundle.putInt("Mukena", 15000);
        bundle.putInt("Piyama", 15000);
        bundle.putInt("Rompi", 10000);
        bundle.putInt("Rok panjang/variasi", 15000);
        bundle.putInt("Rok 3/4", 12500);
        bundle.putInt("Rok pendek", 10000);
        bundle.putInt("Sapu tangan", 7500);
        bundle.putInt("Sarung tutup mobil", 30000);
        bundle.putInt("Sarung bantal kursi", 6000);
        bundle.putInt("Sarung bantal besar", 4000);
        bundle.putInt("Sarung bantal kecil", 2000);
        bundle.putInt("Seprai double", 10000);
        bundle.putInt("Seprai single", 8000);
        bundle.putInt("Selimut tebal", 30000);
        bundle.putInt("Selimut tipis", 15000);
        bundle.putInt("Sepatu kulit/variasi", 35000);
        bundle.putInt("Sepatu", 25000);
        bundle.putInt("Stelan blazer", 30000);
        bundle.putInt("Stelan baju karate", 25000);
        bundle.putInt("Stelan baju olahraga", 20000);
        bundle.putInt("Stelan kebaya", 30000);
        bundle.putInt("Stelan jas", 45000);
        bundle.putInt("Stelan waskat", 25000);
        bundle.putInt("Sweater", 10000);
        bundle.putInt("Tas", 15000);
        bundle.putInt("Tas travel/variasi", 25000);
        bundle.putInt("Topi", 6000);
        bundle.putInt("Waskat", 15000);
        bundle.putInt("Bath towel", 2800);
        bundle.putInt("Bath matt", 1700);
        bundle.putInt("Hand towel", 1500);
        bundle.putInt("Pool towel", 3750);
        bundle.putInt("Pillow case", 1200);
        bundle.putInt("Pillow protector", 1500);
        bundle.putInt("Bolster case", 1200);
        bundle.putInt("Bolster protector", 1500);
        bundle.putInt("Sheet twin", 2800);
        bundle.putInt("Sheet king", 3500);
        bundle.putInt("Sheet king(suite)", 4000);
        bundle.putInt("Dove cover twin", 4000);
        bundle.putInt("Dove cover king", 4500);
        bundle.putInt("Dove cover king(suite)", 4950);
        bundle.putInt("Bathrobe", 4000);
        bundle.putInt("Lobby duster", 2850);
        bundle.putInt("Bed pad", 15000);
        bundle.putInt("Inner duvet", 10000);
        bundle.putInt("Napkin", 500);
        bundle.putInt("Table cloth", 4500);
        bundle.putInt("Table runner", 3000);
        bundle.putInt("Cover chair", 1500);
        bundle.putInt("Moulton", 2500);
        bundle.putInt("Ribbon", 2000);
        bundle.putInt("Skarting", 3000);
    }
}
